export enum PaymentMethod {
  ApplePay = 'apple_pay',
  Bancontact = 'bancontact',
  BankTransfer = 'bank_transfer',
  Belfius = 'belfius',
  CreditCard = 'credit_card',
  DirectDebit = 'direct_debit',
  EPS = 'eps',
  Giropay = 'giropay',
  GooglePay = 'google_pay',
  Ideal = 'ideal',
  KBC = 'kbc',
  Klarna = 'klarna',
  KlarnaPayLater = 'klarna_pay_later',
  KlarnaSliceIt = 'klarna_slice_it',
  Manual = 'manual',
  MyBank = 'mybank',
  PayPal = 'paypal',
  Przelewy24 = 'przelewy24',
  SOFORT = 'sofort',
  Swish = 'swish',
  Voucher = 'voucher',
}
